# Generated by Django 3.0.6 on 2020-05-13 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='datetime_finished',
            field=models.DateTimeField(default=None, verbose_name='Finish datetime'),
        ),
        migrations.AddField(
            model_name='poll',
            name='datetime_start',
            field=models.DateTimeField(default=None, verbose_name='Start datetime'),
        ),
        migrations.AddField(
            model_name='poll',
            name='name',
            field=models.CharField(default='', max_length=250, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='question',
            name='name',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(default='', max_length=250),
        ),
    ]
