# Generated by Django 3.0.6 on 2020-05-13 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20200513_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='name',
        ),
        migrations.AddField(
            model_name='answer',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='choice',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='poll',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.Poll'),
        ),
        migrations.AddField(
            model_name='question',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='poll',
            name='datetime_finished',
            field=models.DateTimeField(default=None, null=True, verbose_name='Finish datetime'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='datetime_start',
            field=models.DateTimeField(default=None, null=True, verbose_name='Start datetime'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('text', 'free text'), ('select_one', 'select one'), ('select_many', 'select many')], max_length=11),
        ),
    ]
