# Generated by Django 3.0.6 on 2020-05-13 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_auto_20200513_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='datetime_finished',
            field=models.DateTimeField(default=None, verbose_name='Finish datetime'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='datetime_start',
            field=models.DateTimeField(default=None, verbose_name='Start datetime'),
        ),
    ]
