# Generated by Django 3.0.6 on 2020-05-13 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_auto_20200514_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='info',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='poll',
            name='datetime_finished',
            field=models.DateTimeField(verbose_name='Finish datetime'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='datetime_start',
            field=models.DateTimeField(verbose_name='Start datetime'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Name'),
        ),
    ]
